/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Aby
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        beratBadan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tinggiBadan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdbperempuan = new javax.swing.JRadioButton();
        btHitung = new javax.swing.JButton();
        btUlangi = new javax.swing.JButton();
        btKelua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        rdblaki = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CEK KESEHATAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 70, 330, 44);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 150, 41, 20);

        jLabel3.setText("Berat Badan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 200, 90, 20);
        jPanel1.add(nama);
        nama.setBounds(320, 150, 380, 26);

        beratBadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratBadanActionPerformed(evt);
            }
        });
        jPanel1.add(beratBadan);
        beratBadan.setBounds(320, 200, 380, 26);

        jLabel4.setText("Tinggi Badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 250, 100, 20);
        jPanel1.add(tinggiBadan);
        tinggiBadan.setBounds(320, 250, 380, 26);

        jLabel5.setText("Jeni Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 300, 100, 20);

        jenisKelamin.add(rdbperempuan);
        rdbperempuan.setText("Perempuan");
        jPanel1.add(rdbperempuan);
        rdbperempuan.setBounds(500, 300, 113, 29);

        btHitung.setText("Hitung");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btHitung);
        btHitung.setBounds(280, 360, 110, 29);

        btUlangi.setText("Ulangi");
        btUlangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUlangiActionPerformed(evt);
            }
        });
        jPanel1.add(btUlangi);
        btUlangi.setBounds(440, 360, 110, 29);

        btKelua.setText("Keluar");
        btKelua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluaActionPerformed(evt);
            }
        });
        jPanel1.add(btKelua);
        btKelua.setBounds(600, 360, 110, 29);

        jLabel6.setText("Berat Badan ideal anda adalah :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 420, 230, 20);
        jPanel1.add(ideal);
        ideal.setBounds(450, 420, 70, 26);

        jLabel7.setText("kg");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 420, 51, 20);

        jLabel8.setText("Hasil analisis kesehatan :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 480, 250, 20);

        hasil.setText("?");
        jPanel1.add(hasil);
        hasil.setBounds(210, 510, 430, 40);

        saran.setText("Saran?");
        jPanel1.add(saran);
        saran.setBounds(210, 560, 430, 40);

        jenisKelamin.add(rdblaki);
        rdblaki.setText("Laki-laki");
        jPanel1.add(rdblaki);
        rdblaki.setBounds(320, 300, 91, 29);

        jPanel2.setBackground(new java.awt.Color(255, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 70, 760, 330);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 700);

        setBounds(0, 0, 1010, 776);
    }// </editor-fold>//GEN-END:initComponents

    private void beratBadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratBadanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_beratBadanActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
        // TODO add your handling code here:
        double t, b, h = 0;
        
        //untuk mengambil nilai tinggi dan berat serta nama
        t = Double.valueOf(tinggiBadan.getText());
        b = Double.valueOf(beratBadan.getText());
        String nm = nama.getText();
        
        //pilihan jenis kelamin
        if(rdblaki.isSelected()){
            h = (t-100);                      
        }else if(rdbperempuan.isSelected()){
            
            h = (t-104);
        }
        String temp = Double.toString(h);
        
        //logika untuk analisa hasil kesehatan 
        if(h<b){
            ideal.setText(temp);
            hasil.setText("Maaf "+nm+" Anda kekurangan berat badan");
            saran.setText("Makan yang banyak dan bergizi");
        }else if(h>b){
            ideal.setText(temp);
            hasil.setText("Maaf "+nm+" Anda kelebihan berat badan");
            saran.setText("Perbanyaklah olahraga dan atur pola makan");
        }else{
            ideal.setText(temp);
            hasil.setText("Berat badan anda sudah ideal");
            saran.setText("Pertahankan");
        
        }           
    }//GEN-LAST:event_btHitungActionPerformed

    private void btUlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUlangiActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        beratBadan.setText("");
        tinggiBadan.setText("");
        ideal.setText("");
        hasil.setText("");
        saran.setText("");
        
        jenisKelamin.clearSelection();
    }//GEN-LAST:event_btUlangiActionPerformed

    private void btKeluaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btKeluaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beratBadan;
    private javax.swing.JButton btHitung;
    private javax.swing.JButton btKelua;
    private javax.swing.JButton btUlangi;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup jenisKelamin;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton rdblaki;
    private javax.swing.JRadioButton rdbperempuan;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggiBadan;
    // End of variables declaration//GEN-END:variables
}
