/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Aby
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihanjurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        varNama = new javax.swing.JTextField();
        varAbsen = new javax.swing.JTextField();
        rdbTKJ = new javax.swing.JRadioButton();
        rdbRpl = new javax.swing.JRadioButton();
        cbProgramming = new javax.swing.JCheckBox();
        cbDesigner = new javax.swing.JCheckBox();
        cbAnimator = new javax.swing.JCheckBox();
        cbVideoediting = new javax.swing.JCheckBox();
        btSubmit = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taHasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 30, 90, 50);

        jLabel2.setText("Nama");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 41, 20);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 44, 20);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 170, 60, 20);

        jLabel5.setText("Hobi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 210, 33, 20);
        getContentPane().add(varNama);
        varNama.setBounds(130, 90, 440, 26);
        getContentPane().add(varAbsen);
        varAbsen.setBounds(130, 130, 440, 26);

        pilihanjurusan.add(rdbTKJ);
        rdbTKJ.setText("TKJ");
        rdbTKJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTKJActionPerformed(evt);
            }
        });
        getContentPane().add(rdbTKJ);
        rdbTKJ.setBounds(130, 170, 59, 29);

        pilihanjurusan.add(rdbRpl);
        rdbRpl.setText("RPL");
        getContentPane().add(rdbRpl);
        rdbRpl.setBounds(330, 170, 59, 29);

        cbProgramming.setText("Programming");
        getContentPane().add(cbProgramming);
        cbProgramming.setBounds(130, 210, 140, 29);

        cbDesigner.setText("Designer");
        getContentPane().add(cbDesigner);
        cbDesigner.setBounds(130, 250, 120, 29);

        cbAnimator.setText("Animator");
        getContentPane().add(cbAnimator);
        cbAnimator.setBounds(330, 210, 99, 29);

        cbVideoediting.setText("Video Editing");
        getContentPane().add(cbVideoediting);
        cbVideoediting.setBounds(330, 250, 140, 29);

        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btSubmit);
        btSubmit.setBounds(60, 300, 150, 29);

        btRemove.setText("Remove");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btRemove);
        btRemove.setBounds(260, 300, 150, 29);

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        getContentPane().add(btExit);
        btExit.setBounds(460, 300, 150, 29);

        jLabel6.setText("Hasil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 370, 34, 20);

        taHasil.setColumns(20);
        taHasil.setRows(5);
        jScrollPane1.setViewportView(taHasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 400, 430, 160);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aby\\Pictures\\Saved Pictures\\gambar-dekoratif-hewan-6.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 80, 560, 480);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 620);

        setBounds(0, 0, 853, 672);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbTKJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTKJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbTKJActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        dispose();
        //System.exit(1);
    }//GEN-LAST:event_btExitActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        // TODO add your handling code here:
        varNama.setText("");
        varAbsen.setText("");
        pilihanjurusan.clearSelection();
        taHasil.setText("");
        cbProgramming.setSelected(false);
        cbDesigner.setSelected(false);
        cbAnimator.setSelected(false);
        cbVideoediting.setSelected(false);
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
        
        String nama = varNama.getText();
        String absen = varAbsen.getText();
        String jurusan;
        String hobi = "";
        
        //untuk pilihan jurusan 
        if (rdbRpl.isSelected())
            jurusan = "RPL";
        else if (rdbTKJ.isSelected())
            jurusan = "TKJ";
        else
            jurusan = " ";
        
        //untuk pilihan checkbox
        if (cbAnimator.isSelected())
            hobi+=cbAnimator.getText()+", ";
        if (cbDesigner.isSelected())
            hobi+=cbDesigner.getText()+", ";
        if (cbProgramming.isSelected())
            hobi+=cbProgramming.getText()+", ";
        if (cbVideoediting.isSelected())
            hobi+=cbVideoediting.getText()+", ";
        
        //untuk hasil
        taHasil.setText("Nama anda :" +nama+"\nAbsen anda :" +absen+ 
                "\nJurusan anda :" +jurusan+ "\nHobi anda :" +hobi);
    }//GEN-LAST:event_btSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btSubmit;
    private javax.swing.JCheckBox cbAnimator;
    private javax.swing.JCheckBox cbDesigner;
    private javax.swing.JCheckBox cbProgramming;
    private javax.swing.JCheckBox cbVideoediting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup pilihanjurusan;
    private javax.swing.JRadioButton rdbRpl;
    private javax.swing.JRadioButton rdbTKJ;
    private javax.swing.JTextArea taHasil;
    private javax.swing.JTextField varAbsen;
    private javax.swing.JTextField varNama;
    // End of variables declaration//GEN-END:variables
}
