/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Aby
 */
public class Latihan5 extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    public Latihan5(String nama, String absen, String jurusan, String alamat, String kelas) {
        initComponents();
        Nama.setText(nama);
        Absen.setText(absen);
        Jurusan.setText(jurusan);
        Alamat.setText(alamat);
        Kelas.setText(kelas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIODATA SISWA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 20, 320, 70);

        Nama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Nama.setForeground(new java.awt.Color(255, 255, 255));
        Nama.setText("Nama");
        jPanel1.add(Nama);
        Nama.setBounds(80, 120, 410, 30);

        Absen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Absen.setForeground(new java.awt.Color(255, 255, 255));
        Absen.setText("Absen");
        jPanel1.add(Absen);
        Absen.setBounds(80, 170, 80, 30);

        Kelas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Kelas.setForeground(new java.awt.Color(255, 255, 255));
        Kelas.setText("Kelas");
        jPanel1.add(Kelas);
        Kelas.setBounds(80, 220, 130, 30);

        Jurusan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Jurusan.setForeground(new java.awt.Color(255, 255, 255));
        Jurusan.setText("Jurusan");
        jPanel1.add(Jurusan);
        Jurusan.setBounds(80, 270, 110, 30);

        Alamat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Alamat.setForeground(new java.awt.Color(255, 255, 255));
        Alamat.setText("Alamat");
        jPanel1.add(Alamat);
        Alamat.setBounds(80, 320, 530, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 630);

        setBounds(0, 0, 1014, 704);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Latihan5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
